# Generated by Django 5.0.3 on 2024-04-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Publihers',
            new_name='Developer',
        ),
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Developers',
            new_name='Publiher',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='games.genre'),
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ManyToManyField(related_name='games', to='games.image'),
        ),
    ]
