# Generated by Django 5.0.3 on 2024-04-27 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_image_rename_publihers_developer_rename_genres_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.publiher'),
        ),
    ]
