# Generated by Django 5.0.3 on 2024-06-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_developer_id_alter_game_publisher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
        migrations.AddField(
            model_name='game',
            name='images',
            field=models.ManyToManyField(related_name='games', to='games.image'),
        ),
        migrations.AddField(
            model_name='game',
            name='main_image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='DefaultName', max_length=100),
        ),
    ]
