# Generated by Django 5.0.3 on 2024-12-06 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_image_remove_game_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinSystemRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('graphics', models.CharField(max_length=100)),
                ('directx', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedSystemRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('graphics', models.CharField(max_length=100)),
                ('directx', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
