# Generated by Django 5.0.3 on 2024-12-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_minsystemrequirements_recommendedsystemrequirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
